version: "2"

services:
  web:
    container_name: dockerdev
    build: ./
    ports:
      - "5050:5050"
    environment:
      DD_DB_HOST: db
    command: /server
    depends_on:
      - db
  db:
    container_name: dockerdev-db
    image: postgres:12.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: togo
    volumes:
      - ./data2.sql:/docker-entrypoint-initdb.d/init.sql